export const HOTELS_ARE_LOADING = 'HOTELS_ARE_LOADING';
export const HOTELS_LOADING_COMPLETE = 'HOTELS_LOADING_COMPLETE';
export const HOTELS_LOADING_ERROR = 'HOTELS_LOADING_ERROR';
export const SET_HOTELS = 'SET_HOTELS';
